#!/usr/bin/env node

const fs = require('node:fs');
const path = require('node:path');

const rootDir = __dirname;
const packageJsonPath = path.join(rootDir, 'package.json');
const environmentPath = path.join(rootDir, 'src', 'environments', 'environment.ts');
const versionTsPath = path.join(rootDir, 'src', 'version.ts');
const publicVersionPath = path.join(rootDir, 'public', 'version.json');

const packageJson = readJson(packageJsonPath);
const environmentSource = fs.readFileSync(environmentPath, 'utf8');
const manual = readBooleanFlag(environmentSource, 'manual');
const automatic = readBooleanFlag(environmentSource, 'automatic');
const previousVersion = packageJson.version;
const generatedAt = new Date().toISOString();

let nextVersion = previousVersion;
let mode = 'manual';

if (manual && automatic) {
  console.warn('[set-version] Both manual and automatic are true. Manual mode has priority.');
}

if (!manual) {
  // Automatic mode bumps only the patch number: 1.2.3 becomes 1.2.4.
  // It'll take version from `package.json`
  nextVersion = incrementPatchVersion(previousVersion);
  packageJson.version = nextVersion;
  mode = 'automatic';
  writeJson(packageJsonPath, packageJson);
}

writeVersionTs(nextVersion, generatedAt);
writePublicVersion(nextVersion, generatedAt, mode);

console.log(`[set-version] ${mode}: package.json ${previousVersion} -> ${nextVersion}`);
console.log(`[set-version] version.ts and public/version.json now use ${nextVersion}`);

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, 'utf8'));
}

function writeJson(filePath, value) {
  fs.writeFileSync(filePath, `${JSON.stringify(value, null, 2)}\n`);
}

function readBooleanFlag(source, flagName) {
  const flagRegex = new RegExp(`${flagName}\\s*:\\s*(true|false)`);
  const match = source.match(flagRegex);

  if (!match) {
    throw new Error(`[set-version] Missing "${flagName}" flag in src/environments/environment.ts.`);
  }

  return match[1] === 'true';
}

function incrementPatchVersion(version) {
  const match = version.match(/^(\d+)\.(\d+)\.(\d+)$/);

  if (!match) {
    throw new Error(
      `[set-version] Expected package.json version to be semver x.y.z, received "${version}".`,
    );
  }

  const major = Number(match[1]);
  const minor = Number(match[2]);
  const patch = Number(match[3]) + 1;

  return `${major}.${minor}.${patch}`;
}

function writeVersionTs(version, generatedAt) {
  const content = `// This file is generated by set-version.js. Keep imports read-only in application code.
export const APP_VERSION = '${version}';
export const APP_VERSION_GENERATED_AT = '${generatedAt}';
`;

  fs.writeFileSync(versionTsPath, content);
}

function writePublicVersion(version, generatedAt, mode) {
  // public/version.json is copied to dist so already-open browsers can compare against the newest build.
  writeJson(publicVersionPath, {
    version,
    generatedAt,
    mode,
  });
}
